// animalImages.js
export const animalImages = {
    'Afrikanischer Löwe': 'images/lowe.png',
    'Afrikanischer Elefant': 'images/elefant.png',
    'Masai-Giraffe': 'images/giraffe.png',
    'Steppenzebra': 'images/zebra.png',
    'Blaues Gnu': 'images/gnu.png',
    'Gepard': 'images/gepard.png',
    'Spitzmaulnashorn': 'images/nashorn.png',
    'Braune Hyäne': 'images/hyane.png',
    'Afrikanischer Strauß': 'images/strauss.png',
    'Dromedar': 'images/dromedar.png',
    'Fennek': 'images/fennek.png',
    'Dünenskorpion': 'images/skorpion.png',
    'Sandchamäleon': 'images/chamaleon.png',
    'Erdmännchen': 'images/erdmannchen.png',
    'Palmatogecko': 'images/gecko.png',
    'Nubischer Geier': 'images/geier.png',
    'Goldene Radspinne': 'images/spinne.png',
    'Westliche Diamant-Klapperschlange': 'images/klapperschlange.png',
    'Blauwal': 'images/blauwal.png',
    'Gemeiner Delfin': 'images/delfin.png',
    'Weißer Hai': 'images/hai.png',
    'Kurzschnäuziges Seepferdchen': 'images/seepferdchen.png',
    'Pazifischer Riesenkrake': 'images/krake.png',
    'Clownfisch': 'images/clownfisch.png',
    'Unechte Karettschildkröte': 'images/schildkrote.png',
    'Stechrochen': 'images/rochen.png',
    'Kompassqualle': 'images/qualle.png',
    'Schwarzer Panther': 'images/panther.png',
    'Fischertukan': 'images/tukan.png' ,
    'Kapuzineraffe': 'images/affe.png' ,
    'Hoffmanns Faultier': 'images/faultier.png' ,
    'Großer Ameisenbär': 'images/ameisenbar.png' ,
    'Ara': 'images/ara.png' ,
    'Blauer Morphofalter': 'images/schmetterling.png' ,
    'Pfeilgiftfrosch': 'images/frosch.png' ,
    'Papageienschlange': 'images/schlange.png', 
  };
