// animalImages.js
export const animalImagesColored = {
    'Afrikanischer Löwe': 'images/lowe-farbig.png',
    'Afrikanischer Elefant': 'images/elefant-farbig.png',
    'Masai-Giraffe': 'images/giraffe-farbig.png',
    'Steppenzebra': 'images/zebra-farbig.png',
    'Blaues Gnu': 'images/gnu-farbig.png',
    'Gepard': 'images/gepard-farbig.png',
    'Spitzmaulnashorn': 'images/nashorn-farbig.png',
    'Braune Hyäne': 'images/hyane-farbig.png',
    'Afrikanischer Strauß': 'images/strauss-farbig.png',
    'Dromedar': 'images/dromedar-farbig.png',
    'Fennek': 'images/fennek-farbig.png',
    'Dünenskorpion': 'images/skorpion-farbig.png',
    'Sandchamäleon': 'images/chamaleon-farbig.png',
    'Erdmännchen': 'images/erdmannchen-farbig.png',
    'Palmatogecko': 'images/gecko-farbig.png',
    'Nubischer Geier': 'images/geier-farbig.png',
    'Goldene Radspinne': 'images/spinne-farbig.png',
    'Westliche Diamant-Klapperschlange': 'images/klapperschlange-farbig.png',
    'Blauwal': 'images/blauwal-farbig.png',
    'Gemeiner Delfin': 'images/delfin-farbig.png',
    'Weißer Hai': 'images/hai-farbig.png',
    'Kurzschnäuziges Seepferdchen': 'images/seepferdchen-farbig.png',
    'Pazifischer Riesenkrake': 'images/krake-farbig.png',
    'Clownfisch': 'images/clownfisch-farbig.png',
    'Unechte Karettschildkröte': 'images/schildkrote-farbig.png',
    'Stechrochen': 'images/rochen-farbig.png',
    'Kompassqualle': 'images/qualle-farbig.png',
    'Schwarzer Panther': 'images/panther-farbig.png',
    'Fischertukan': 'images/tukan-farbig.png' ,
    'Kapuzineraffe': 'images/affe-farbig.png' ,
    'Hoffmanns Faultier': 'images/faultier-farbig.png' ,
    'Großer Ameisenbär': 'images/ameisenbar-farbig.png' ,
    'Ara': 'images/ara-farbig.png' ,
    'Blauer Morphofalter': 'images/schmetterling-farbig.png' ,
    'Pfeilgiftfrosch': 'images/frosch-farbig.png' ,
    'Papageienschlange': 'images/schlange-farbig.png', 
  };
